# 应用配置
app:
  host: "127.0.0.1"
  port: ":3000"
  embed: false
  root: "../webui/dist/spa"
  prefork: false # prefork是否启用，默认true

# 服务配置
service:
  enable_swagger: true # 是否启用swagger，默认false
  enable_cors: true # 是否启用跨域，默认true
  enable_gzip: true # 是否启用gzip，默认true
  enable_rate_limiter: true # 是否启用限流，默认true
  enable_recovery: true # 是否启用恢复，默认true
  enable_validate: true # 是否启用验证，默认true
  enable_i18n: true # 是否启用国际化，默认true
  enable_secure: true # 是否启用安全，默认true
  enable_helmet: true # 是否启用helmet，默认true
  enable_compress: true # 是否启用压缩，默认true
  enable_debug: true # 是否启用调试，默认true
  enable_metrics: true # 是否启用指标，默认true
  enable_pprof: true # 是否启用pprof，默认true
  enable_tracer: true # 是否启用跟踪，默认true
  enable_grpc: true # 是否启用grpc，默认true
  enable_http2: true # 是否启用http2，默认true
  enable_http3: true # 是否启用http3，默认true
  enable_etag: true # 是否启用etag，默认true
  
# 数据库配置
database:
  type: "mysql"
  enable: true
  host: "127.0.0.1"
  port: 3306
  dbname: "wmjtyd-iot"
  user: "wmjtyd-iot"
  password: "wmjtyd-iot"
  chartset: "utf8mb4"
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  max_life_time: 3600 # 连接可复用的最大时间(s)
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称
  table_prefix: "wmjtyd_" # 表名前缀

# redis配置
redis:
  enable: false
  host: "127.0.0.1"
  port: "6379"
  database: 0
  password: ""

# TDengine 配置
taos:
  enable: false
  host: "localhost"
  port: 6030
  database: "wmjtyd-iot"
  user: "root"
  password: "taosdata"

# 日志配置
log:
  enable: true
  #日志文件的位置，也就是路径
  filename: "./logs/log.txt"
  #在进行切割之前，日志文件的最大大小（以MB为单位）
  maxSize: 10
  #保留旧文件的最大个数
  maxBackups: 10
  #保留旧文件的最大天数
  maxAges: 180
  #是否压缩/归档旧文件
  compress: false

#单位(60秒*60*24) 24小时
jwt:
  name: "Authorization"
  secret: "wmjtyd-iotavHGsfjcSb9ldv5BXzo8C6qsRlx6"
  expire: 72 # hour
  secret_key: "secret"
  secret_key_expire_minutes_count: 500
  refresh_key: "refresh"
  refresh_key_expire_hours_count: 720

# MQTT配置
mqtt:
  host: "192.168.0.80"
  port: 1883
  username: "wmjtyd-iot"
  password: "wmjtyd-iot"
  client_id: "wmjtyd-iot_mqtt01"
  keepalive: 60
  qos: 1
  namespace: "wmjtyd-iot/v1.0"